Helper.printOneToN(4) ; 

System.debug('Helper.sumOfOneToN(100)  value is : ' 
                + Helper.sumOfOneToN(100)   );

System.debug('Helper.sumOfOneToN(500)  value is : ' 
                + Helper.sumOfOneToN(500)   );

System.debug('Helper.getOneToNList(7) value is : ' 
                    + Helper.getOneToNList(7));

System.debug('Helper.getOneToNList(4) value is : ' 
                    + Helper.getOneToNList(4));



