//8. Create an String Array with 10 elements and print them in reverse order

String[] stringArray = new String[10];
stringArray[0] = 'string0';
stringArray[1] = 'string1';
stringArray[2] = 'string2';
stringArray[3] = 'string3';
stringArray[4] = 'string4';
stringArray[5] = 'string5';
stringArray[6] = 'string6';
stringArray[7] = 'string7';
stringArray[8] = 'string8';
stringArray[9] = 'string9';

Integer count = 0;

while (count >= 0) {
  System.debug(stringArray[count]);
  count--;
}



